// Generated by gencpp from file reflex_msgs/FingerPressure.msg
// DO NOT EDIT!


#ifndef REFLEX_MSGS_MESSAGE_FINGERPRESSURE_H
#define REFLEX_MSGS_MESSAGE_FINGERPRESSURE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace reflex_msgs
{
template <class ContainerAllocator>
struct FingerPressure_
{
  typedef FingerPressure_<ContainerAllocator> Type;

  FingerPressure_()
    : sensor()  {
      sensor.assign(0);
  }
  FingerPressure_(const ContainerAllocator& _alloc)
    : sensor()  {
  (void)_alloc;
      sensor.assign(0);
  }



   typedef boost::array<uint16_t, 9>  _sensor_type;
  _sensor_type sensor;





  typedef boost::shared_ptr< ::reflex_msgs::FingerPressure_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::reflex_msgs::FingerPressure_<ContainerAllocator> const> ConstPtr;

}; // struct FingerPressure_

typedef ::reflex_msgs::FingerPressure_<std::allocator<void> > FingerPressure;

typedef boost::shared_ptr< ::reflex_msgs::FingerPressure > FingerPressurePtr;
typedef boost::shared_ptr< ::reflex_msgs::FingerPressure const> FingerPressureConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::reflex_msgs::FingerPressure_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::reflex_msgs::FingerPressure_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::reflex_msgs::FingerPressure_<ContainerAllocator1> & lhs, const ::reflex_msgs::FingerPressure_<ContainerAllocator2> & rhs)
{
  return lhs.sensor == rhs.sensor;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::reflex_msgs::FingerPressure_<ContainerAllocator1> & lhs, const ::reflex_msgs::FingerPressure_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace reflex_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::reflex_msgs::FingerPressure_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::reflex_msgs::FingerPressure_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::reflex_msgs::FingerPressure_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::reflex_msgs::FingerPressure_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::reflex_msgs::FingerPressure_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::reflex_msgs::FingerPressure_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::reflex_msgs::FingerPressure_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fe4417140692b62d71a7ba82897b83f5";
  }

  static const char* value(const ::reflex_msgs::FingerPressure_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfe4417140692b62dULL;
  static const uint64_t static_value2 = 0x71a7ba82897b83f5ULL;
};

template<class ContainerAllocator>
struct DataType< ::reflex_msgs::FingerPressure_<ContainerAllocator> >
{
  static const char* value()
  {
    return "reflex_msgs/FingerPressure";
  }

  static const char* value(const ::reflex_msgs::FingerPressure_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::reflex_msgs::FingerPressure_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# message for pressure on a single finger\n"
"uint16[9] sensor    	# The sensors enumerate from the base of the finger to the tip\n"
"						# There are 5 on the proximal link, 4 on the distal\n"
;
  }

  static const char* value(const ::reflex_msgs::FingerPressure_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::reflex_msgs::FingerPressure_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sensor);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FingerPressure_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::reflex_msgs::FingerPressure_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::reflex_msgs::FingerPressure_<ContainerAllocator>& v)
  {
    s << indent << "sensor[]" << std::endl;
    for (size_t i = 0; i < v.sensor.size(); ++i)
    {
      s << indent << "  sensor[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.sensor[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // REFLEX_MSGS_MESSAGE_FINGERPRESSURE_H
