(cl:defpackage reflex_one_msgs-srv
  (:use )
  (:export
   "SETSPEED"
   "<SETSPEED-REQUEST>"
   "SETSPEED-REQUEST"
   "<SETSPEED-RESPONSE>"
   "SETSPEED-RESPONSE"
   "SETTACTILETHRESHOLD"
   "<SETTACTILETHRESHOLD-REQUEST>"
   "SETTACTILETHRESHOLD-REQUEST"
   "<SETTACTILETHRESHOLD-RESPONSE>"
   "SETTACTILETHRESHOLD-RESPONSE"
  ))

