// Generated by gencpp from file ros_gazebo_plugin_comm/Vector7d.msg
// DO NOT EDIT!


#ifndef ROS_GAZEBO_PLUGIN_COMM_MESSAGE_VECTOR7D_H
#define ROS_GAZEBO_PLUGIN_COMM_MESSAGE_VECTOR7D_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_gazebo_plugin_comm
{
template <class ContainerAllocator>
struct Vector7d_
{
  typedef Vector7d_<ContainerAllocator> Type;

  Vector7d_()
    : data()  {
      data.assign(0.0);
  }
  Vector7d_(const ContainerAllocator& _alloc)
    : data()  {
  (void)_alloc;
      data.assign(0.0);
  }



   typedef boost::array<float, 7>  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::ros_gazebo_plugin_comm::Vector7d_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_gazebo_plugin_comm::Vector7d_<ContainerAllocator> const> ConstPtr;

}; // struct Vector7d_

typedef ::ros_gazebo_plugin_comm::Vector7d_<std::allocator<void> > Vector7d;

typedef boost::shared_ptr< ::ros_gazebo_plugin_comm::Vector7d > Vector7dPtr;
typedef boost::shared_ptr< ::ros_gazebo_plugin_comm::Vector7d const> Vector7dConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_gazebo_plugin_comm::Vector7d_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_gazebo_plugin_comm::Vector7d_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_gazebo_plugin_comm

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'ros_gazebo_plugin_comm': ['/home/work/code_repository/ros_packages/src/ros_gazebo_plugin_comm/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_gazebo_plugin_comm::Vector7d_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_gazebo_plugin_comm::Vector7d_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_gazebo_plugin_comm::Vector7d_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_gazebo_plugin_comm::Vector7d_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_gazebo_plugin_comm::Vector7d_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_gazebo_plugin_comm::Vector7d_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_gazebo_plugin_comm::Vector7d_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e4844fe6885794a5295df1d81cbae79f";
  }

  static const char* value(const ::ros_gazebo_plugin_comm::Vector7d_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe4844fe6885794a5ULL;
  static const uint64_t static_value2 = 0x295df1d81cbae79fULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_gazebo_plugin_comm::Vector7d_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_gazebo_plugin_comm/Vector7d";
  }

  static const char* value(const ::ros_gazebo_plugin_comm::Vector7d_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_gazebo_plugin_comm::Vector7d_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[7] data\n\
";
  }

  static const char* value(const ::ros_gazebo_plugin_comm::Vector7d_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_gazebo_plugin_comm::Vector7d_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Vector7d_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_gazebo_plugin_comm::Vector7d_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_gazebo_plugin_comm::Vector7d_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_GAZEBO_PLUGIN_COMM_MESSAGE_VECTOR7D_H
