// Generated by gencpp from file reflex_one_msgs/SetSpeed.msg
// DO NOT EDIT!


#ifndef REFLEX_ONE_MSGS_MESSAGE_SETSPEED_H
#define REFLEX_ONE_MSGS_MESSAGE_SETSPEED_H

#include <ros/service_traits.h>


#include <reflex_one_msgs/SetSpeedRequest.h>
#include <reflex_one_msgs/SetSpeedResponse.h>


namespace reflex_one_msgs
{

struct SetSpeed
{

typedef SetSpeedRequest Request;
typedef SetSpeedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetSpeed
} // namespace reflex_one_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::reflex_one_msgs::SetSpeed > {
  static const char* value()
  {
    return "04171ebc3d171407826cbe90dea5b330";
  }

  static const char* value(const ::reflex_one_msgs::SetSpeed&) { return value(); }
};

template<>
struct DataType< ::reflex_one_msgs::SetSpeed > {
  static const char* value()
  {
    return "reflex_one_msgs/SetSpeed";
  }

  static const char* value(const ::reflex_one_msgs::SetSpeed&) { return value(); }
};


// service_traits::MD5Sum< ::reflex_one_msgs::SetSpeedRequest> should match
// service_traits::MD5Sum< ::reflex_one_msgs::SetSpeed >
template<>
struct MD5Sum< ::reflex_one_msgs::SetSpeedRequest>
{
  static const char* value()
  {
    return MD5Sum< ::reflex_one_msgs::SetSpeed >::value();
  }
  static const char* value(const ::reflex_one_msgs::SetSpeedRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::reflex_one_msgs::SetSpeedRequest> should match
// service_traits::DataType< ::reflex_one_msgs::SetSpeed >
template<>
struct DataType< ::reflex_one_msgs::SetSpeedRequest>
{
  static const char* value()
  {
    return DataType< ::reflex_one_msgs::SetSpeed >::value();
  }
  static const char* value(const ::reflex_one_msgs::SetSpeedRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::reflex_one_msgs::SetSpeedResponse> should match
// service_traits::MD5Sum< ::reflex_one_msgs::SetSpeed >
template<>
struct MD5Sum< ::reflex_one_msgs::SetSpeedResponse>
{
  static const char* value()
  {
    return MD5Sum< ::reflex_one_msgs::SetSpeed >::value();
  }
  static const char* value(const ::reflex_one_msgs::SetSpeedResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::reflex_one_msgs::SetSpeedResponse> should match
// service_traits::DataType< ::reflex_one_msgs::SetSpeed >
template<>
struct DataType< ::reflex_one_msgs::SetSpeedResponse>
{
  static const char* value()
  {
    return DataType< ::reflex_one_msgs::SetSpeed >::value();
  }
  static const char* value(const ::reflex_one_msgs::SetSpeedResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REFLEX_ONE_MSGS_MESSAGE_SETSPEED_H
