// Generated by gencpp from file reflex_msgs2/DistalRotation.msg
// DO NOT EDIT!


#ifndef REFLEX_MSGS2_MESSAGE_DISTALROTATION_H
#define REFLEX_MSGS2_MESSAGE_DISTALROTATION_H

#include <ros/service_traits.h>


#include <reflex_msgs2/DistalRotationRequest.h>
#include <reflex_msgs2/DistalRotationResponse.h>


namespace reflex_msgs2
{

struct DistalRotation
{

typedef DistalRotationRequest Request;
typedef DistalRotationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DistalRotation
} // namespace reflex_msgs2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::reflex_msgs2::DistalRotation > {
  static const char* value()
  {
    return "96436694e12dc909600e6760ed1174cd";
  }

  static const char* value(const ::reflex_msgs2::DistalRotation&) { return value(); }
};

template<>
struct DataType< ::reflex_msgs2::DistalRotation > {
  static const char* value()
  {
    return "reflex_msgs2/DistalRotation";
  }

  static const char* value(const ::reflex_msgs2::DistalRotation&) { return value(); }
};


// service_traits::MD5Sum< ::reflex_msgs2::DistalRotationRequest> should match
// service_traits::MD5Sum< ::reflex_msgs2::DistalRotation >
template<>
struct MD5Sum< ::reflex_msgs2::DistalRotationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::reflex_msgs2::DistalRotation >::value();
  }
  static const char* value(const ::reflex_msgs2::DistalRotationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::reflex_msgs2::DistalRotationRequest> should match
// service_traits::DataType< ::reflex_msgs2::DistalRotation >
template<>
struct DataType< ::reflex_msgs2::DistalRotationRequest>
{
  static const char* value()
  {
    return DataType< ::reflex_msgs2::DistalRotation >::value();
  }
  static const char* value(const ::reflex_msgs2::DistalRotationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::reflex_msgs2::DistalRotationResponse> should match
// service_traits::MD5Sum< ::reflex_msgs2::DistalRotation >
template<>
struct MD5Sum< ::reflex_msgs2::DistalRotationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::reflex_msgs2::DistalRotation >::value();
  }
  static const char* value(const ::reflex_msgs2::DistalRotationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::reflex_msgs2::DistalRotationResponse> should match
// service_traits::DataType< ::reflex_msgs2::DistalRotation >
template<>
struct DataType< ::reflex_msgs2::DistalRotationResponse>
{
  static const char* value()
  {
    return DataType< ::reflex_msgs2::DistalRotation >::value();
  }
  static const char* value(const ::reflex_msgs2::DistalRotationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REFLEX_MSGS2_MESSAGE_DISTALROTATION_H
