// Generated by gencpp from file reflex_msgs2/SetSpeed.msg
// DO NOT EDIT!


#ifndef REFLEX_MSGS2_MESSAGE_SETSPEED_H
#define REFLEX_MSGS2_MESSAGE_SETSPEED_H

#include <ros/service_traits.h>


#include <reflex_msgs2/SetSpeedRequest.h>
#include <reflex_msgs2/SetSpeedResponse.h>


namespace reflex_msgs2
{

struct SetSpeed
{

typedef SetSpeedRequest Request;
typedef SetSpeedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetSpeed
} // namespace reflex_msgs2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::reflex_msgs2::SetSpeed > {
  static const char* value()
  {
    return "7e4d6fd69113a7a3ab5caa755082c6b7";
  }

  static const char* value(const ::reflex_msgs2::SetSpeed&) { return value(); }
};

template<>
struct DataType< ::reflex_msgs2::SetSpeed > {
  static const char* value()
  {
    return "reflex_msgs2/SetSpeed";
  }

  static const char* value(const ::reflex_msgs2::SetSpeed&) { return value(); }
};


// service_traits::MD5Sum< ::reflex_msgs2::SetSpeedRequest> should match
// service_traits::MD5Sum< ::reflex_msgs2::SetSpeed >
template<>
struct MD5Sum< ::reflex_msgs2::SetSpeedRequest>
{
  static const char* value()
  {
    return MD5Sum< ::reflex_msgs2::SetSpeed >::value();
  }
  static const char* value(const ::reflex_msgs2::SetSpeedRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::reflex_msgs2::SetSpeedRequest> should match
// service_traits::DataType< ::reflex_msgs2::SetSpeed >
template<>
struct DataType< ::reflex_msgs2::SetSpeedRequest>
{
  static const char* value()
  {
    return DataType< ::reflex_msgs2::SetSpeed >::value();
  }
  static const char* value(const ::reflex_msgs2::SetSpeedRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::reflex_msgs2::SetSpeedResponse> should match
// service_traits::MD5Sum< ::reflex_msgs2::SetSpeed >
template<>
struct MD5Sum< ::reflex_msgs2::SetSpeedResponse>
{
  static const char* value()
  {
    return MD5Sum< ::reflex_msgs2::SetSpeed >::value();
  }
  static const char* value(const ::reflex_msgs2::SetSpeedResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::reflex_msgs2::SetSpeedResponse> should match
// service_traits::DataType< ::reflex_msgs2::SetSpeed >
template<>
struct DataType< ::reflex_msgs2::SetSpeedResponse>
{
  static const char* value()
  {
    return DataType< ::reflex_msgs2::SetSpeed >::value();
  }
  static const char* value(const ::reflex_msgs2::SetSpeedResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REFLEX_MSGS2_MESSAGE_SETSPEED_H
