// Generated by gencpp from file reflex_msgs2/SetSpeedRequest.msg
// DO NOT EDIT!


#ifndef REFLEX_MSGS2_MESSAGE_SETSPEEDREQUEST_H
#define REFLEX_MSGS2_MESSAGE_SETSPEEDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace reflex_msgs2
{
template <class ContainerAllocator>
struct SetSpeedRequest_
{
  typedef SetSpeedRequest_<ContainerAllocator> Type;

  SetSpeedRequest_()
    : motor()  {
      motor.assign(0.0);
  }
  SetSpeedRequest_(const ContainerAllocator& _alloc)
    : motor()  {
  (void)_alloc;
      motor.assign(0.0);
  }



   typedef boost::array<double, 4>  _motor_type;
  _motor_type motor;





  typedef boost::shared_ptr< ::reflex_msgs2::SetSpeedRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::reflex_msgs2::SetSpeedRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetSpeedRequest_

typedef ::reflex_msgs2::SetSpeedRequest_<std::allocator<void> > SetSpeedRequest;

typedef boost::shared_ptr< ::reflex_msgs2::SetSpeedRequest > SetSpeedRequestPtr;
typedef boost::shared_ptr< ::reflex_msgs2::SetSpeedRequest const> SetSpeedRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::reflex_msgs2::SetSpeedRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::reflex_msgs2::SetSpeedRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::reflex_msgs2::SetSpeedRequest_<ContainerAllocator1> & lhs, const ::reflex_msgs2::SetSpeedRequest_<ContainerAllocator2> & rhs)
{
  return lhs.motor == rhs.motor;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::reflex_msgs2::SetSpeedRequest_<ContainerAllocator1> & lhs, const ::reflex_msgs2::SetSpeedRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace reflex_msgs2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::reflex_msgs2::SetSpeedRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::reflex_msgs2::SetSpeedRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::reflex_msgs2::SetSpeedRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::reflex_msgs2::SetSpeedRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::reflex_msgs2::SetSpeedRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::reflex_msgs2::SetSpeedRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::reflex_msgs2::SetSpeedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7e4d6fd69113a7a3ab5caa755082c6b7";
  }

  static const char* value(const ::reflex_msgs2::SetSpeedRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7e4d6fd69113a7a3ULL;
  static const uint64_t static_value2 = 0xab5caa755082c6b7ULL;
};

template<class ContainerAllocator>
struct DataType< ::reflex_msgs2::SetSpeedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "reflex_msgs2/SetSpeedRequest";
  }

  static const char* value(const ::reflex_msgs2::SetSpeedRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::reflex_msgs2::SetSpeedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# message for calling hand commands\n"
"float64[4] motor\n"
;
  }

  static const char* value(const ::reflex_msgs2::SetSpeedRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::reflex_msgs2::SetSpeedRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.motor);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetSpeedRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::reflex_msgs2::SetSpeedRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::reflex_msgs2::SetSpeedRequest_<ContainerAllocator>& v)
  {
    s << indent << "motor[]" << std::endl;
    for (size_t i = 0; i < v.motor.size(); ++i)
    {
      s << indent << "  motor[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.motor[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // REFLEX_MSGS2_MESSAGE_SETSPEEDREQUEST_H
