// Generated by gencpp from file reflex_msgs2/SetTactileThreshold.msg
// DO NOT EDIT!


#ifndef REFLEX_MSGS2_MESSAGE_SETTACTILETHRESHOLD_H
#define REFLEX_MSGS2_MESSAGE_SETTACTILETHRESHOLD_H

#include <ros/service_traits.h>


#include <reflex_msgs2/SetTactileThresholdRequest.h>
#include <reflex_msgs2/SetTactileThresholdResponse.h>


namespace reflex_msgs2
{

struct SetTactileThreshold
{

typedef SetTactileThresholdRequest Request;
typedef SetTactileThresholdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetTactileThreshold
} // namespace reflex_msgs2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::reflex_msgs2::SetTactileThreshold > {
  static const char* value()
  {
    return "b2d8992c5dc80dcc6a9e73ef557b5387";
  }

  static const char* value(const ::reflex_msgs2::SetTactileThreshold&) { return value(); }
};

template<>
struct DataType< ::reflex_msgs2::SetTactileThreshold > {
  static const char* value()
  {
    return "reflex_msgs2/SetTactileThreshold";
  }

  static const char* value(const ::reflex_msgs2::SetTactileThreshold&) { return value(); }
};


// service_traits::MD5Sum< ::reflex_msgs2::SetTactileThresholdRequest> should match
// service_traits::MD5Sum< ::reflex_msgs2::SetTactileThreshold >
template<>
struct MD5Sum< ::reflex_msgs2::SetTactileThresholdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::reflex_msgs2::SetTactileThreshold >::value();
  }
  static const char* value(const ::reflex_msgs2::SetTactileThresholdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::reflex_msgs2::SetTactileThresholdRequest> should match
// service_traits::DataType< ::reflex_msgs2::SetTactileThreshold >
template<>
struct DataType< ::reflex_msgs2::SetTactileThresholdRequest>
{
  static const char* value()
  {
    return DataType< ::reflex_msgs2::SetTactileThreshold >::value();
  }
  static const char* value(const ::reflex_msgs2::SetTactileThresholdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::reflex_msgs2::SetTactileThresholdResponse> should match
// service_traits::MD5Sum< ::reflex_msgs2::SetTactileThreshold >
template<>
struct MD5Sum< ::reflex_msgs2::SetTactileThresholdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::reflex_msgs2::SetTactileThreshold >::value();
  }
  static const char* value(const ::reflex_msgs2::SetTactileThresholdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::reflex_msgs2::SetTactileThresholdResponse> should match
// service_traits::DataType< ::reflex_msgs2::SetTactileThreshold >
template<>
struct DataType< ::reflex_msgs2::SetTactileThresholdResponse>
{
  static const char* value()
  {
    return DataType< ::reflex_msgs2::SetTactileThreshold >::value();
  }
  static const char* value(const ::reflex_msgs2::SetTactileThresholdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REFLEX_MSGS2_MESSAGE_SETTACTILETHRESHOLD_H
