// Generated by gencpp from file reflex_msgs2/SetTactileThresholdResponse.msg
// DO NOT EDIT!


#ifndef REFLEX_MSGS2_MESSAGE_SETTACTILETHRESHOLDRESPONSE_H
#define REFLEX_MSGS2_MESSAGE_SETTACTILETHRESHOLDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace reflex_msgs2
{
template <class ContainerAllocator>
struct SetTactileThresholdResponse_
{
  typedef SetTactileThresholdResponse_<ContainerAllocator> Type;

  SetTactileThresholdResponse_()
    {
    }
  SetTactileThresholdResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::reflex_msgs2::SetTactileThresholdResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::reflex_msgs2::SetTactileThresholdResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetTactileThresholdResponse_

typedef ::reflex_msgs2::SetTactileThresholdResponse_<std::allocator<void> > SetTactileThresholdResponse;

typedef boost::shared_ptr< ::reflex_msgs2::SetTactileThresholdResponse > SetTactileThresholdResponsePtr;
typedef boost::shared_ptr< ::reflex_msgs2::SetTactileThresholdResponse const> SetTactileThresholdResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::reflex_msgs2::SetTactileThresholdResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::reflex_msgs2::SetTactileThresholdResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace reflex_msgs2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::reflex_msgs2::SetTactileThresholdResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::reflex_msgs2::SetTactileThresholdResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::reflex_msgs2::SetTactileThresholdResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::reflex_msgs2::SetTactileThresholdResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::reflex_msgs2::SetTactileThresholdResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::reflex_msgs2::SetTactileThresholdResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::reflex_msgs2::SetTactileThresholdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::reflex_msgs2::SetTactileThresholdResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::reflex_msgs2::SetTactileThresholdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "reflex_msgs2/SetTactileThresholdResponse";
  }

  static const char* value(const ::reflex_msgs2::SetTactileThresholdResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::reflex_msgs2::SetTactileThresholdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::reflex_msgs2::SetTactileThresholdResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::reflex_msgs2::SetTactileThresholdResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetTactileThresholdResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::reflex_msgs2::SetTactileThresholdResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::reflex_msgs2::SetTactileThresholdResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // REFLEX_MSGS2_MESSAGE_SETTACTILETHRESHOLDRESPONSE_H
