# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from reflex_one_msgs/Command.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import reflex_one_msgs.msg

class Command(genpy.Message):
  _md5sum = "cdbebc0876ac872616d6c63603a84a2e"
  _type = "reflex_one_msgs/Command"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """PoseCommand pose
VelocityCommand velocity

================================================================================
MSG: reflex_one_msgs/PoseCommand
# Position in radians of various motors
float64 f1
float64 f2
float64 f3
float64 preshape1
float64 preshape2

================================================================================
MSG: reflex_one_msgs/VelocityCommand
# Velocity in radians/second of various motors
float64 f1
float64 f2
float64 f3
float64 preshape1
float64 preshape2
"""
  __slots__ = ['pose','velocity']
  _slot_types = ['reflex_one_msgs/PoseCommand','reflex_one_msgs/VelocityCommand']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       pose,velocity

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Command, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.pose is None:
        self.pose = reflex_one_msgs.msg.PoseCommand()
      if self.velocity is None:
        self.velocity = reflex_one_msgs.msg.VelocityCommand()
    else:
      self.pose = reflex_one_msgs.msg.PoseCommand()
      self.velocity = reflex_one_msgs.msg.VelocityCommand()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_10d().pack(_x.pose.f1, _x.pose.f2, _x.pose.f3, _x.pose.preshape1, _x.pose.preshape2, _x.velocity.f1, _x.velocity.f2, _x.velocity.f3, _x.velocity.preshape1, _x.velocity.preshape2))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.pose is None:
        self.pose = reflex_one_msgs.msg.PoseCommand()
      if self.velocity is None:
        self.velocity = reflex_one_msgs.msg.VelocityCommand()
      end = 0
      _x = self
      start = end
      end += 80
      (_x.pose.f1, _x.pose.f2, _x.pose.f3, _x.pose.preshape1, _x.pose.preshape2, _x.velocity.f1, _x.velocity.f2, _x.velocity.f3, _x.velocity.preshape1, _x.velocity.preshape2,) = _get_struct_10d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_10d().pack(_x.pose.f1, _x.pose.f2, _x.pose.f3, _x.pose.preshape1, _x.pose.preshape2, _x.velocity.f1, _x.velocity.f2, _x.velocity.f3, _x.velocity.preshape1, _x.velocity.preshape2))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.pose is None:
        self.pose = reflex_one_msgs.msg.PoseCommand()
      if self.velocity is None:
        self.velocity = reflex_one_msgs.msg.VelocityCommand()
      end = 0
      _x = self
      start = end
      end += 80
      (_x.pose.f1, _x.pose.f2, _x.pose.f3, _x.pose.preshape1, _x.pose.preshape2, _x.velocity.f1, _x.velocity.f2, _x.velocity.f3, _x.velocity.preshape1, _x.velocity.preshape2,) = _get_struct_10d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_10d = None
def _get_struct_10d():
    global _struct_10d
    if _struct_10d is None:
        _struct_10d = struct.Struct("<10d")
    return _struct_10d
