(cl:in-package reflex_msgs2-msg)
(cl:export '(ACC_OFFSET_F1-VAL
          ACC_OFFSET_F1
          ACC_OFFSET_F2-VAL
          ACC_OFFSET_F2
          ACC_OFFSET_F3-VAL
          ACC_OFFSET_F3
          ACC_OFFSET_PALM-VAL
          ACC_OFFSET_PALM
          MAG_OFFSET_F1-VAL
          MAG_OFFSET_F1
          MAG_OFFSET_F2-VAL
          MAG_OFFSET_F2
          MAG_OFFSET_F3-VAL
          MAG_OFFSET_F3
          MAG_OFFSET_PALM-VAL
          MAG_OFFSET_PALM
          GYR_OFFSET_F1-VAL
          GYR_OFFSET_F1
          GYR_OFFSET_F2-VAL
          GYR_OFFSET_F2
          GYR_OFFSET_F3-VAL
          GYR_OFFSET_F3
          GYR_OFFSET_PALM-VAL
          GYR_OFFSET_PALM
          ACC_RADIUS-VAL
          ACC_RADIUS
          GYR_RADIUS-VAL
          GYR_RADIUS
))