(cl:defpackage reflex_msgs2-srv
  (:use )
  (:export
   "DISTALROTATION"
   "<DISTALROTATION-REQUEST>"
   "DISTALROTATION-REQUEST"
   "<DISTALROTATION-RESPONSE>"
   "DISTALROTATION-RESPONSE"
   "SETSPEED"
   "<SETSPEED-REQUEST>"
   "SETSPEED-REQUEST"
   "<SETSPEED-RESPONSE>"
   "SETSPEED-RESPONSE"
   "SETTACTILETHRESHOLD"
   "<SETTACTILETHRESHOLD-REQUEST>"
   "SETTACTILETHRESHOLD-REQUEST"
   "<SETTACTILETHRESHOLD-RESPONSE>"
   "SETTACTILETHRESHOLD-RESPONSE"
  ))

